#! /bin/bash

DIR=$(date +"%Y-%m-%d-%T")

CUDA_VISIBLE_DEVICES='0'

mkdir -p results/$DIR/bayesian/4var-nonlinear/fixedcov-zeromean-uniform
mkdir -p results/$DIR/bayesian/4var-nonlinear/fixedcov-nonzeromean-uniform
mkdir -p results/$DIR/bayesian/4var-nonlinear/fullcov-zeromean-uniform
mkdir -p results/$DIR/bayesian/4var-nonlinear/fullcov-nonzeromean-uniform

N_DATA_SAMPLES=1000
N_MCMC_SAMPLES=1000
N_MCMC_WARMUP=250
MAX_EM_ITERS=5
MAX_MLE_ITERS=1000
NUM_CHAINS=4
MIN_CLUSTERS=2
MAX_CLUSTERS=2


# 4 variable nonlinear zero-mean noise
python run_experiment.py \
    --n_data_samples $N_DATA_SAMPLES \
    --n_mcmc_samples $N_MCMC_SAMPLES \
    --n_mcmc_warmup $N_MCMC_WARMUP \
    --max_em_iters $MAX_EM_ITERS \
    --max_mle_iters $MAX_MLE_ITERS \
    --min_clusters $MIN_CLUSTERS \
    --max_clusters $MAX_CLUSTERS \
    --num_chains $NUM_CHAINS \
    --dataset '4var-nonlinear' \
    --nonlinear \
    --proposal_type 'uniform' \
    --output_path results/$DIR/bayesian/4var-nonlinear/fixedcov-zeromean-uniform

# 4 variable nonlinear nonzero-mean noise
python run_experiment.py \
    --n_data_samples $N_DATA_SAMPLES \
    --n_mcmc_samples $N_MCMC_SAMPLES \
    --n_mcmc_warmup $N_MCMC_WARMUP \
    --max_em_iters $MAX_EM_ITERS \
    --max_mle_iters $MAX_MLE_ITERS \
    --min_clusters $MIN_CLUSTERS \
    --max_clusters $MAX_CLUSTERS \
    --num_chains $NUM_CHAINS \
    --dataset '4var-nonlinear' \
    --nonlinear \
    --nonzero_centered \
    --proposal_type 'uniform' \
    --output_path results/$DIR/bayesian/4var-nonlinear/fixedcov-nonzeromean-uniform

# 4 variable nonlinear full covariance optimization zero-mean noise
python run_experiment.py \
    --n_data_samples $N_DATA_SAMPLES \
    --n_mcmc_samples $N_MCMC_SAMPLES \
    --n_mcmc_warmup $N_MCMC_WARMUP \
    --max_em_iters $MAX_EM_ITERS \
    --max_mle_iters $MAX_MLE_ITERS \
    --min_clusters $MIN_CLUSTERS \
    --max_clusters $MAX_CLUSTERS \
    --num_chains $NUM_CHAINS \
    --optimize_covariance \
    --full_covariance \
    --dataset '4var-nonlinear' \
    --nonlinear \
    --proposal_type 'uniform' \
    --output_path results/$DIR/bayesian/4var-nonlinear/fullcov-zeromean-uniform

# 4 variable nonlinear full covariance optimization nonzero-mean noise
python run_experiment.py \
    --n_data_samples $N_DATA_SAMPLES \
    --n_mcmc_samples $N_MCMC_SAMPLES \
    --n_mcmc_warmup $N_MCMC_WARMUP \
    --max_em_iters $MAX_EM_ITERS \
    --max_mle_iters $MAX_MLE_ITERS \
    --min_clusters $MIN_CLUSTERS \
    --max_clusters $MAX_CLUSTERS \
    --num_chains $NUM_CHAINS \
    --optimize_covariance \
    --full_covariance \
    --dataset '4var-nonlinear' \
    --nonlinear \
    --nonzero_centered \
    --proposal_type 'uniform' \
    --output_path results/$DIR/bayesian/4var-nonlinear/fullcov-nonzeromean-uniform
